---
name: "Build Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Build Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/irccloud/irccat
          tags: |
            type=semver,pattern={{version}}
            type=sha
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check Formatting
        run: gofmt -d -e .
      - name: Tests
        run: go test -v ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Dockerfile
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
